# Generated by Django 4.0.5 on 2022-07-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('region', models.CharField(max_length=75, verbose_name='Регион')),
                ('phone_number', models.CharField(max_length=13, verbose_name='Номер телефона')),
                ('status', models.CharField(choices=[('new', 'new'), ('pending', 'pending'), ('cancelled', 'cancelled')], default='new', max_length=20)),
                ('source', models.CharField(choices=[('telegram', 'telegram'), ('site', 'site')], default='site', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('region_name', models.CharField(max_length=75, verbose_name='Регион')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('user_id', models.BigIntegerField(verbose_name='ID пользователя')),
                ('name', models.CharField(max_length=50, verbose_name='Никнейм')),
                ('username', models.CharField(max_length=150, null=True, verbose_name='Юзернейм')),
                ('language', models.CharField(max_length=5, verbose_name='Язык')),
            ],
        ),
    ]
