# Generated by Django 4.0.5 on 2022-06-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regions',
            new_name='Region',
        ),
    ]
