# Generated by Django 4.0.5 on 2022-06-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_rename_regions_region'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Application',
        ),
    ]
