# Generated by Django 4.0.5 on 2022-06-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_rename_user_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='region_name',
            field=models.CharField(max_length=75, verbose_name='Регион'),
        ),
    ]
