# Generated by Django 4.0.5 on 2022-06-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_region_region_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user_id', models.BigIntegerField(verbose_name='ID пользователя')),
                ('name', models.CharField(max_length=50, verbose_name='Никнейм')),
                ('username', models.CharField(max_length=150, verbose_name='Юзернейм')),
            ],
        ),
    ]
