# Generated by Django 4.0.5 on 2022-06-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_user_created_at_alter_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default=1, max_length=5, verbose_name='Язык'),
            preserve_default=False,
        ),
    ]
